language: node_js
node_js:
  - "0.12"

notifications:
  email:
    recipients:
      - amcmillan@yieldbot.com
    on_success: always
    on_failure: always

script:
  - "npm install"
  - "npm run lint"
  - "npm run test"
#  - "npm run publish"